application: helloworld
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /termcloud
  static_dir: termcloud

- url: /.*
  script: helloworld.py
